sudo: false
language: node_js
node_js:
- '6'
- '5'
- '4'
os:
- osx
- linux
cache:
  directories:
  - node_modules
before_install:
- npm config set spin false
script: npm run test:cover
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
after_success: bash scripts/deploy
deploy:
- provider: npm
  email: dylan947@gmail.com
  api_key:
    secure: Y7mnpEAfhjICTKIjfAyCMz11irbNQYGA+0gZ768uBadtn2A8IEuVSc6SUOQwcssCGlpWNzLw9h28uOl209HeVruH8u4jqhtATBQMH38StpCCaUZWD64bQblgu2tzBhSrrChag3bAmRuiKKyhmebpV59Ag6koaqR9WRtYeeCQRdmChcyhwLVlTiP8TNz4uJMeBAVWDqAXkNBWsWOQpRfK77XIPC8P8H8nOigGVVWt4zjKX2qVbFc45Yn8JTtbofKpx2CU5IYspk/eMKuRHwbcx1zXJ4DMRi4/iLDcsqkl0WoyIGkSfxkpbvfJtUrrg9N2JLtka+JvLpL7c27qxY2RSyPK3L3On0tFRGIAHPmur93zXALaaztiN8SIrw2MoGYoRjqzhRf2RHHNwbxS7HW+xr98ymfNXfJfSgZHsS4wOnpm8cm8TLFVJQatu9Cn4pgo/QEEJvdY77zF1tRVrHQzl+CP9zDzPFM0ntqgO1sbmccxxL6pI4TMB4IrWHje2Y9s5lrWRWRSUGZ+evnDkoOGjoaCS5UW03Qf7s4H1ACZDV5ib9/IHw/9hxGyLfP6IrGY4RT1vg51Eqe3uoRHfJpeeAn3socTcuMH9oio7PWXHZ5uyGtGFyu+Z9sSQRibDd2TxenTRZn0tPbhwREionvY9Hf0gFexvtP34IR62GQywrI=
  on:
    tags: true
    repo: dylanfoster/parch
env:
  global:
  - GH_REF: github.com/parch-js/parch-js.github.io
  - secure: JqZAWvrcGYiHDckX04b5wkBNCe43ePnmDlMi6oI0S50LbNxdxt5hs8SnkXL/WR9ps/exXSWhlwKT/L2EtVHHkfCqBO3R7XKxZgcPR9QuimO1vPZR/3o+hi2OsPXSobrqT8Vzm8DLSCyCZzaDaCyt/G5rf+Z//rvrmCyLNkr1ws+A7oM2jI3+XSgn7hrDgzNgEvsDHIHkeuRqeSdoNcL2UO0aTkyHJqYvTXV3kqZL+OAPYfzzIvUb3NPVrUO1/qIBPPW3e1gM9LO9blexRKooxJoGhOsV81lf5zeqaiZyptND881vk7IatCnZeYpFHngnksLZSUTYAgtzw+6nOB4qpxfPgF3qOxmPkQa84qBjpZv54HcJW2xNG/DUNPPrV6l7tvUZnaKZVGK8+b3qW1sWJrWxvcWlIkR4ga39kA5GM9mdUcogJNMZsFoAUxeiNTYBQZb8zuL/mWLw78VRm6BOqfnqqIecJq+TeObd868Kddv6Kj3zy5rYaC3bifpYRXxn0J4wz8D2s3qLft5z0dSAevWdr63Kom6MIfjkfpk0eO+C1UOtjveNKiqL5Zy/ydqoWdwbjDQPD0vY0RH2NcYlm74v93iggwoRRa4XXEDdG7ie0/GO3tEyqPYvsBOUTCSuCvDQ8Y9COUwXzQUsfR0xs6pjCgRjL5CJSU9evmGWt3Q=
