sudo: false
language: node_js
node_js:
  - node
  - "5"
  - "4"
  - "0.12"

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"

os:
  - osx
  - linux

script: npm run test:cover

after_script:
  cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
